# Generated by Django 4.2 on 2023-05-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_user_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateField(default='2023-05-02')),
                ('puntuacion', models.IntegerField(choices=[('ONE_STAR', 1), ('TWO_STARS', 2), ('THREE_STARS', 3), ('FOUR_STARS', 4), ('FIVE_STARS', 5)])),
                ('likes', models.IntegerField(default=0, null=True)),
                ('dislikes', models.IntegerField(default=0, null=True)),
                ('cantidad_votantes', models.IntegerField(default=0, null=True)),
                ('nick_autor', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews_Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reseña', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('username', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default='2023-05-02')),
                ('comentador', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_reseña', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
