# Generated by Django 4.2 on 2023-05-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_punctuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='votes',
        ),
    ]
