# Generated by Django 4.2 on 2023-05-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_remove_review_creation_date_remove_review_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='punctuation',
            field=models.IntegerField(choices=[('ONE_STAR', 1), ('TWO_STARS', 2), ('THREE_STARS', 3), ('FOUR_STARS', 4), ('FIVE_STARS', 5)], default=3, help_text='Puntuación'),
        ),
    ]
