# Generated by Django 4.2 on 2023-05-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_review_punctuation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='id_reseña',
            new_name='id_review',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comentador',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='reviews_username',
            old_name='id_reseña',
            new_name='id_review',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default='No comment', max_length=500),
        ),
        migrations.AddField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(default='2023-05-11'),
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default='2023-05-11'),
        ),
        migrations.CreateModel(
            name='ReviewLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('id_review', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('username', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
