# Generated by Django 4.2 on 2023-05-12 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_rename_id_reseña_comments_id_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_nickname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(default='2023-05-12'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default='2023-05-12'),
        ),
    ]
