# Generated by Django 4.2 on 2023-06-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(default='2023-06-16'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default='2023-06-16'),
        ),
    ]
