# Generated by Django 4.2 on 2023-06-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_comments_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='object_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
