# Generated by Django 4.2 on 2023-06-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_review_object_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(default='2023-06-25'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default='2023-06-25'),
        ),
    ]
