# Generated by Django 4.2 on 2023-06-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_comments_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlikes',
            old_name='id_review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewlikes',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateField(default='2023-06-30'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(default='2023-06-30'),
        ),
    ]
